collections_config:
  pages:
    path: ''
    name: pages
    label: Pages
    icon: wysiwyg
    filter:
      include:
        - index.html
    _enabled_editors:
      - visual
      - content
      - data

  gallery:
    path: _gallery
    name: gallery
    label: Gallery Photos
    icon: image
    _enabled_editors:
      - data
    _inputs:
      title:
        type: text
        label: Photo Title
      category:
        type: select
        label: Category
        options:
          values:
            - exterior
            - interior
      image:
        type: image
        label: Photo
        uploads_dir: photos/Bentley_files

uploads_dir: photos/Bentley_files
