backend:
  name: github
  repo: Savx-alt/nuevo-detailing
  branch: main

media_folder: "photos/Bentley_files"
public_folder: "photos/Bentley_files"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "photos/Bentley_files"
    create: true
    delete: true
    fields:
      - { label: "Photo Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Exterior", "Interior"] }
